// bangbangboom-webapp/src/game/mapping/components/fast-render/timingpad.vue
<template>
    <div class="pad flex">
        <div v-for="o in padopacities" :key="o.id">
            <div :style="{opacity: o.opacity}"></div>
        </div>
    </div>
</template>

<script lang="ts">
import Vue from "vue";
import { PlayState, minTicker, SoundTime } from "../../state";
import { MinTicker } from "@/game/core/Ticker";
import { lazyObject } from "@/tools/functions";

import tickurl from "../../../assets/timing_tick.wav";
import tackurl from "../../../assets/timing_tack.wav";
import { TimePoint } from "../../../core/MapCore";
import { GameMapState } from "../../gamemapstate";

const sounds = lazyObject({
    tick: () => new Howl({ src: tickurl }),
    tack: () => new Howl({ src: tackurl })
});

export default Vue.extend({
    props: {
        mute: { type: Boolean },
        selected: { type: TimePoint }
    },
    computed: {
        padopacities: function(): Array<{ id: number; opacity: number }> {
            const tp =
                this.selected ||
                GameMapState.s.getCurrentTimePoint(PlayState.position);
            if (!tp) return [];
            const beatinfo = tp.getBeat(PlayState.position);
            if (!beatinfo) return [];

            const r: number[] = [];
            for (let i = 1; i <= tp.bpb; i++) {
                if (i === beatinfo.beat) {
                    let opacity = (0.2 - beatinfo.offset) * 5;
                    if (opacity < 0) opacity = 0;
                    r.push(opacity);
                    // r.push(1);
                } else r.push(0);
            }
            return r.map((v, i) => ({ id: i, opacity: v }));
        }
    },
    methods: {
        mintick: function() {
            // defined later
        }
    },
    mounted: function() {
        const soundloaded = sounds.tick && sounds.tack;
        this.$watch(
            () => SoundTime.value,
            (n, p) => {
                if (!PlayState.music || !PlayState.playing || this.mute) return;
                const tp =
                    this.selected || GameMapState.s.getCurrentTimePoint(n);
                if (!tp) return;
                const beatinfo = tp.getBeat(n);
                if (!beatinfo) return;
                const off = n - p;
                if (off > 0.1) return;
                if (beatinfo.offset < off) {
                    if (beatinfo.beat === 1) sounds.tick.play();
                    else sounds.tack.play();
                }
            }
        );
        minTicker.Start();
    },
    beforeDestroy: function() {
        minTicker.Stop();
    }
});
</script>

<style scoped>
.pad {
    height: 80px;
    padding: 10px;
    transform: translate(0, 0);
}
.pad > * {
    flex-grow: 1;
    height: 100%;
    margin: 10px;
    border: solid 3px cornflowerblue;
    border-radius: 5px;
    overflow: hidden;
}
.pad :first-child {
    border-color: darkorange;
}
.pad > * > * {
    width: 100%;
    height: 100%;
    background-color: cornflowerblue;
}
.pad :first-child > * {
    background-color: darkorange;
}
</style>

// bangbangboom-webapp/src/Mapping/Components/TimingPad.tsx
import React, { useRef, useEffect } from "react"
import { makeStyles } from "@material-ui/core"
import { useObserver, useAsObservableSource, useLocalStore } from "mobx-react-lite"
import { lazyObject, MakeArray } from "../../Global/Utils"
import { Howl } from "howler"
import { Assets } from "../Assets"
import { TimePoint } from "../core/MapCore"
import { GameMapState } from "../GameMapState"
import { PlayState } from "../MappingState"
import { autorun } from "mobx"

const useStyles = makeStyles(theme => ({
  root: {
    display: "flex",
    alignItems: "center",
    height: 80,
    padding: 10,
    transform: "translate(0, 0)",
    "&>*": {
      flexGrow: 1,
      height: "100%",
      margin: 10,
      border: "solid 3px cornflowerblue",
      borderRadius: 3,
      overflow: "hidden",
    },
    "& :first-child": {
      borderColor: "darkorange",
    },
    "&>*>*": {
      width: "100%",
      height: "100%",
      backgroundColor: "cornflowerblue",
      willChange: "opacity",
      opacity: 0,
    },
    "& :first-child>*": {
      backgroundColor: "darkorange",
    },
  }
}))

const sounds = lazyObject({
  tick: () => new Howl({ src: Assets.timing_tick }),
  tack: () => new Howl({ src: Assets.timing_tack })
})

function getCurrentTimePoint(t: number) {
  let prev: TimePoint | null = null
  for (const tp of GameMapState.map.timepoints) {
    if (tp.offset > t) break
    prev = tp
  }
  return prev
}

function getBeat(tp: TimePoint, t: number) {
  if (t < tp.offset) return null
  const bt = 60 / tp.bpm
  const bar = bt * tp.bpb
  let off = t - tp.offset
  const barCount = Math.floor(off / bar)
  off -= barCount * bar
  const beatCount = Math.floor(off / bt)
  off -= beatCount * bt
  return {
    bar: barCount + 1,
    beat: beatCount + 1,
    offset: off,
    totalbeat: barCount * tp.bpb + beatCount + 1,
  }
}

export type TimingPadProps = { mute: boolean, selectedTp: null | TimePoint }

export const TimingPad = (props: TimingPadProps) => {
  const cn = useStyles()

  const p = useAsObservableSource(props)
  const s = useLocalStore(() => ({
    get tp() { return p.selectedTp || getCurrentTimePoint(PlayState.position) },
    get beatinfo() { return s.tp && getBeat(s.tp, PlayState.position) },
    get bars() { return (s.tp && s.tp.bpb) || 0 },
    get opacities() {
      if (!s.beatinfo || !s.tp) return []
      const l = []
      for (let i = 1; i <= s.tp.bpb; i++) {
        if (i === s.beatinfo.beat) {
          let opacity = (0.2 - s.beatinfo.offset) * 5
          if (opacity < 0) opacity = 0
          l.push(opacity)
        } else l.push(0)
      }
      return l
    },
    lastinfo: null as ReturnType<typeof getBeat>,
    lastposition: -1
  }))

  const ref = useRef<HTMLDivElement>(null)

  useEffect(() => autorun(() => {
    const { tick, tack } = sounds
    if (!p.mute && PlayState.music && PlayState.playing && s.tp && s.beatinfo) {
      const dt = PlayState.position - s.lastposition
      if (dt > 0 && dt < 0.4) {
        if (s.lastinfo)
          if (s.lastinfo.bar !== s.beatinfo.bar || s.lastinfo.beat !== s.beatinfo.beat) {
            if (s.beatinfo.beat === 1) tick.play()
            else tack.play()
          }
      }
      s.lastposition = PlayState.position
      s.lastinfo = s.beatinfo
    }
    const div = ref.current
    if (div)
      s.opacities.forEach((v, i) => {
        const d = div.children[i] as HTMLDivElement
        if (!d) return
        const c = d.firstChild as HTMLDivElement
        if (!c) return
        c.style.opacity = v as any
      })
  }), [s, p])

  return useObserver(() => (
    <div className={cn.root} ref={ref}>
      {MakeArray(s.bars).map(v =>
        <div key={v}>
          <div></div>
        </div>)}
    </div>
  ))
}
