// bangbangboom-webapp/src/game/mapping/components/fast-render/tracks.vue
<template>
    <div @wheel="scroll">
        <div class="panel" ref="panel" @mousemove="mouseMove" @click="click" @dragover="allowdrop" @drop="drop">
            <div class="layer">
                <div class="line" v-for="i in [15,25,35,45,55,65,75,85]" :key="i" :style="{left: i + '%'}"></div>
            </div>
            <div class="layer">
                <div class="time" v-for="t in timeList" :key="t" :style="{bottom: bottompx(t)}">{{ t | time }}</div>
            </div>
            <div class="layer">
                <div class="timepoint" v-for="t in timepoints" :key="t.track" :style="{bottom: bottompx(t.time)}">
                    <div style="position: absolute;left: 0">{{t.time | time}}</div>
                    <div style="position: absolute;right: 0">{{t.bpm}}</div>
                </div>
            </div>
            <div class="layer">
                <div
                    class="beatline1"
                    v-for="b in beatline1"
                    :key="b.time"
                    :style="{bottom: bottompx(b.time)}"
                >{{b.name}}</div>
            </div>
            <div class="layer" v-show="division % 2 === 0">
                <div class="subline beatline2" v-for="b in beatline2" :key="b" :style="{bottom: bottompx(b)}"></div>
            </div>
            <div class="layer" v-show="division % 3 === 0">
                <div class="subline beatline3" v-for="b in beatline3" :key="b" :style="{bottom: bottompx(b)}"></div>
            </div>
            <div class="layer" v-show="division % 4 === 0">
                <div class="subline beatline4" v-for="b in beatline4" :key="b" :style="{bottom: bottompx(b)}"></div>
            </div>
            <div class="layer" :style="{transform: this.mirror ? 'scaleX(-1)' : ''}">
                <img class="note preview" v-if="previewNote" :src="previewNote.src" :style="previewNote" />
                <img
                    class="note preview"
                    v-if="previewSlideNote && previewNote"
                    :src="previewNote.src"
                    :style="previewSlideNote"
                />
            </div>
            <div class="layer">
                <progressbar class="progress" :time-height-factor="timeHeightFactor"></progressbar>
            </div>
            <notes
                class="layer"
                :timeHeightFactor="timeHeightFactor"
                :tool="tool"
                :width="width"
                @drag="drag"
                @newmid="newmid"
                :mirror="mirror"
            ></notes>
        </div>
    </div>
</template>

<script lang="ts">
import Vue, { VNode } from "vue";
import { PlayState } from "../../state";
import {
    SelectPosition,
    timelist,
    beatline1,
    beatline3,
    beatline2,
    beatline4,
    nearestBeatTime
} from "./state";
import { GameMapState, Actions } from "../../gamemapstate";
import { assets } from "@/game/assets/assetsmap";
import { trackid, Note, TimePoint } from "@/game/core/MapCore";
import notes from "./noteslayer";
import progressbar from "./tracksprogress";

export default Vue.extend({
    components: {
        notes: notes,
        progressbar
    },
    props: {
        timeHeightFactor: {
            type: Number,
            required: true
        },
        division: {
            type: Number,
            required: true
        },
        tool: {
            type: String,
            required: true
        },
        mirror: {
            type: Boolean,
            default: false
        }
    },
    data: function() {
        return {
            width: 0,
            mouseTime: 0,
            mouseLane: -1,
            dropNote: {
                tpid: "",
                noteid: "",
                slideid: "" as string | undefined
            },
            previewSlideNote: null as { left: string; bottom: string } | null,
            previewSlideNoteData: {
                offset: 0,
                tp: "",
                lane: 0
            },
            active: true
        };
    },
    computed: {
        position: () => SelectPosition.p,
        paddedDuration: () => PlayState.duration * 1.2,
        timeList: function(): number[] {
            return timelist(2, this.paddedDuration);
        },
        timepoints: () => GameMapState.s.timepoints,
        beatline1: () => beatline1(),
        beatline2: () => beatline2(),
        beatline3: () => beatline3(),
        beatline4: () => beatline4(),
        previewNote: function(): any {
            if (this.tool === "none") return null;
            if (this.mouseLane < 0) return null;
            const t = nearestBeatTime(this.mouseTime, this.division);
            if (!t) return null;
            let src = "";
            switch (this.tool) {
                case "normal":
                    src = assets.note_normal;
                    break;
                case "flick":
                    src = assets.note_flick;
                    break;
                case "slide":
                    src = assets.note_long;
                    break;
            }
            return {
                left: this.mouseLane * 10 + 15 + "%",
                bottom: this.bottompx(t.time),
                src: src
            };
        },
        assets: () => assets
    },
    methods: {
        resize: function() {
            const c = this.$refs.panel as HTMLElement;
            this.width = c.clientWidth;
        },
        bottompx: function(t: number) {
            return this.timeHeightFactor * t + "px";
        },
        scroll: function(e: WheelEvent) {
            e.preventDefault();
            e.stopPropagation();
            const dt = e.deltaY / this.timeHeightFactor;
            let target = SelectPosition.p - dt;
            if (target < 0) target = 0;
            if (target > PlayState.duration) target = PlayState.duration;
            SelectPosition.p = target;
        },
        mouseMove: function(e: MouseEvent) {
            const p = this.$refs.panel as HTMLElement;
            const rect = p.getBoundingClientRect();
            const y = rect.bottom - e.clientY;
            const x = e.clientX - rect.left;
            this.mouseTime = y / this.timeHeightFactor;
            let l = Math.floor((x / rect.width) * 10 - 1.5);
            if (l < 0) l = -1;
            if (l > 6) l = -1;
            this.mouseLane = this.mirror ? 6 - l : l;
        },
        click: function(e: MouseEvent) {
            if (this.tool === "none") return;
            if (this.mouseLane < 0) return;
            const t = nearestBeatTime(this.mouseTime, this.division);
            if (!t) return;
            switch (this.tool) {
                case "normal":
                    Actions.addSingle(
                        t.timepoint,
                        this.mouseLane,
                        t.beatoffset,
                        trackid()
                    );
                    break;
                case "flick":
                    Actions.addFlick(
                        t.timepoint,
                        this.mouseLane,
                        t.beatoffset,
                        trackid()
                    );
                    break;
                case "slide":
                    if (this.previewSlideNote) {
                        const d = this.previewSlideNoteData;
                        if (d.tp === t.timepoint) {
                            Actions.addSlide(
                                t.timepoint,
                                d.lane,
                                d.offset,
                                this.mouseLane,
                                t.beatoffset,
                                trackid(),
                                trackid(),
                                trackid()
                            );
                        }
                        this.previewSlideNote = null;
                    } else {
                        this.previewSlideNote = {
                            bottom: this.previewNote.bottom as string,
                            left: this.previewNote.left as string
                        };
                        this.previewSlideNoteData = {
                            offset: t.beatoffset,
                            lane: this.mouseLane,
                            tp: t.timepoint
                        };
                    }
                    break;
            }
        },
        newmid: function(e: MouseEvent, tpid: string, slideid: string) {
            this.mouseMove(e);
            if (this.mouseLane < 0) return;
            const t = nearestBeatTime(this.mouseTime, this.division);
            if (!t || t.timepoint !== tpid) return;
            Actions.addSlideMid(
                tpid,
                slideid,
                this.mouseLane,
                t.beatoffset,
                trackid()
            );
        },
        allowdrop: function(e: DragEvent) {
            e.preventDefault();
        },
        drag: function(
            e: DragEvent,
            tpid: string,
            noteid: string,
            slideid?: string
        ) {
            this.dropNote.tpid = tpid;
            this.dropNote.noteid = noteid;
            this.dropNote.slideid = slideid;
        },
        drop: function(e: DragEvent) {
            e.preventDefault();
            this.mouseMove(e);
            const t = nearestBeatTime(this.mouseTime, this.division);
            if (!t) return;
            if (!this.dropNote.slideid) {
                Actions.moveSingleOrFlick(
                    this.dropNote.tpid,
                    this.dropNote.noteid,
                    this.mouseLane,
                    t.beatoffset,
                    t.timepoint
                );
            } else {
                if (this.dropNote.tpid === t.timepoint)
                    Actions.moveSlideNote(
                        this.dropNote.tpid,
                        this.dropNote.slideid,
                        this.dropNote.noteid,
                        this.mouseLane,
                        t.beatoffset
                    );
            }
        }
    },
    mounted: function() {
        const p = this.$refs.panel as HTMLElement;
        this.$watch(
            () => Math.floor(this.position * this.timeHeightFactor),
            n => {
                if (!this.active) return;
                p.style.transform = `translateY(${n}px)`;
            },
            { immediate: true }
        );
        this.$watch(
            () => this.timeHeightFactor * this.paddedDuration,
            n => {
                p.style.height = n + "px";
            },
            { immediate: true }
        );
        this.resize();
        this.$watch(() => this.tool, n => (this.previewSlideNote = null));
        window.addEventListener("resize", this.resize);
    },
    activated: function() {
        this.active = true;
    },
    deactivated: function() {
        this.active = false;
    },
    beforeDestroy: function() {
        window.removeEventListener("resize", this.resize);
    }
});
</script>

<style scoped>
.panel {
    width: 100%;
    position: absolute;
    bottom: 0;
    will-change: transform;
}
.layer {
    width: 100%;
    height: 100%;
    position: absolute;
    pointer-events: none;
}
.line {
    border-left: 1px solid lightgray;
    height: 100%;
    position: absolute;
}
.time {
    position: absolute;
}
.timepoint {
    position: absolute;
    color: aquamarine;
    width: 95%;
    border-bottom: 1px aquamarine solid;
    height: 1.5em;
}
.beatline1 {
    position: absolute;
    text-align: right;
    width: 80%;
    right: 5%;
    border-bottom: 1px lightgray solid;
}
.subline {
    position: absolute;
    width: 70%;
    left: 15%;
}
.beatline2 {
    border-bottom: 1px solid gray;
}
.beatline3 {
    border-bottom: 1px dashed firebrick;
}
.beatline4 {
    border-bottom: 1px dashed darkslateblue;
}
.note.preview {
    opacity: 0.5;
    z-index: 0;
}
.progress {
    position: absolute;
    width: 80%;
    left: 10%;
    border-bottom: 2px solid red;
    bottom: 0;
    will-change: transform;
    opacity: 0.7;
}
</style>

<style>
.note {
    transform: translateY(50%) scale(1.2);
    width: 10%;
    position: absolute;
    pointer-events: auto;
    z-index: 1;
    min-height: 10px;
}
.slide-among {
    background: greenyellow;
    opacity: 0.2;
    width: 10%;
    position: absolute;
    pointer-events: auto;
}
</style>

// bangbangboom-webapp/src/Mapping/Components/Tracks.tsx
import React, { useMemo, useCallback, useEffect, useRef } from "react"
import { makeStyles } from "@material-ui/core"
import { useNoteStyles, NotesLayer } from "./Tracks.NotesLayer"
import { useObserver, useLocalStore } from "mobx-react-lite"
import { PlayState, seek } from "../MappingState"
import { GameMapState, Actions } from "../GameMapState"
import { MakeArray, TimeToString } from "../../Global/Utils"
import { BeatLines } from "./Tracks.BeatLines"
import { nearestBeatTime } from "./Utils"
import { Assets } from "../Assets"
import clsx from "clsx"
import { ProgressLine } from "./Tracks.ProgressLine"
import { uuid } from "../core/Utils"
import { TracksState } from "../Pages/Tracks.State"
import { autorun } from "mobx"

const useStyles = makeStyles(theme => ({
  panel: {
    width: "100%",
    position: "absolute",
    bottom: 0,
    willChange: "transform"
  },
  layer: {
    width: "100%",
    height: "100%",
    position: "absolute",
    pointerEvents: "none",
  },
  line: {
    borderLeft: "1px solid lightgray",
    height: "100%",
    position: "absolute",
    pointerEvents: "none"
  },
  time: {
    position: "absolute"
  },
  timepoint: {
    position: "absolute",
    color: "aquamarine",
    width: "95%",
    borderBottom: "1px aquamarine solid",
    height: "1.5em"
  },
}))

const VerticalLineLefts = MakeArray(90, 15, 10)

export const Tracks = ({ className = "" }) => {
  const cn = useStyles()
  const ncn = useNoteStyles()

  const s = useLocalStore(() => ({
    mouse: {
      time: 0,
      lane: -1,
    },
    touch: {
      touching: false,
      startY: 0,
      startPos: 0
    },
    dropnote: {
      tpid: "",
      noteid: "",
      slideid: "",
    },
    previewSlide: {
      style: null as { left: string, bottom: string } | null,
      data: { offset: 0, tpid: "", lane: 0 }
    },
    get paddedDuration() { return PlayState.duration * 1.2 },
    get bottompx() { return (t: number) => TracksState.timeHeightFactor * t + "px" },
    get previewNote() {
      if (TracksState.tool === "none") return null
      if (s.mouse.lane < 0) return null
      const t = nearestBeatTime(s.mouse.time, TracksState.division)
      if (!t) return null
      let src = ""
      switch (TracksState.tool) {
        case "normal": src = Assets.note_normal; break
        case "flick": src = Assets.note_flick; break
        case "slide": src = Assets.note_long; break
      }
      return {
        style: {
          left: s.mouse.lane * 10 + 15 + "%",
          bottom: s.bottompx(t.time),
        },
        src
      }
    },
    get panelStyle() {
      return {
        height: TracksState.timeHeightFactor * s.paddedDuration + "px",
      }
    },
  }))

  const panelref = useRef<HTMLDivElement>(null)
  useEffect(() => {
    return autorun(() => {
      if (panelref.current)
        panelref.current.style.transform = `translateY(${TracksState.timeHeightFactor * TracksState.viewposition}px)`
    })
  }, [])

  const handleMouseMove = (e: React.MouseEvent<HTMLDivElement>) => {
    const p = e.currentTarget
    const rect = p.getBoundingClientRect()
    const y = rect.bottom - e.clientY
    const x = e.clientX - rect.left
    s.mouse.time = y / TracksState.timeHeightFactor
    let l = Math.floor((x / rect.width) * 10 - 1.5)
    if (l < 0) l = -1
    if (l > 6) l = -1
    s.mouse.lane = TracksState.mirror ? 6 - l : l
  }

  const handleClick = (e: React.MouseEvent<HTMLDivElement>) => {
    if (TracksState.tool === "none") return
    handleMouseMove(e)
    if (s.mouse.lane < 0) return
    const t = nearestBeatTime(s.mouse.time, TracksState.division)
    if (!t) return
    switch (TracksState.tool) {
      case "normal":
        Actions.addSingle(t.timepoint, s.mouse.lane, t.beatoffset, uuid()); break
      case "flick":
        Actions.addFlick(t.timepoint, s.mouse.lane, t.beatoffset, uuid()); break
      case "slide":
        if (s.previewSlide.style) {
          const d = s.previewSlide.data
          if (d.tpid === t.timepoint) {
            Actions.addSlide(t.timepoint, d.lane, d.offset, s.mouse.lane,
              t.beatoffset, uuid(), uuid(), uuid())
          }
          s.previewSlide.style = null
        } else {
          if (!s.previewNote) break
          s.previewSlide.style = Object.assign({}, s.previewNote.style)
          s.previewSlide.data = { offset: t.beatoffset, lane: s.mouse.lane, tpid: t.timepoint }
        }
        break
    }
  }

  const handleDragOver = (e: React.DragEvent<HTMLDivElement>) => {
    e.preventDefault()
  }

  const handleDrop = (e: React.DragEvent<HTMLDivElement>) => {
    e.preventDefault()
    handleMouseMove(e)
    if (!s.dropnote.noteid || s.mouse.lane < 0) return
    const t = nearestBeatTime(s.mouse.time, TracksState.division)
    if (!t) return
    if (!s.dropnote.slideid) {
      Actions.moveSingleOrFlick(s.dropnote.tpid, s.dropnote.noteid, s.mouse.lane, t.beatoffset, t.timepoint)
    } else {
      Actions.moveSlideNote(s.dropnote.tpid, s.dropnote.slideid, s.dropnote.noteid, s.mouse.lane, t.beatoffset)
    }
  }

  const handleScroll = (e: React.WheelEvent) => {
    // e.preventDefault() // ???
    e.stopPropagation()
    const dt = e.deltaY / TracksState.timeHeightFactor
    let target = TracksState.viewposition - dt
    if (target < 0) target = 0
    if (target > PlayState.duration) target = PlayState.duration
    if (TracksState.tracking) seek(target)
    else TracksState.viewposition = target
  }

  const handleTouchStart = (e: React.TouchEvent) => {
    if (s.touch.touching) return
    s.touch.touching = true
    s.touch.startY = e.targetTouches[0].clientY
    s.touch.startPos = TracksState.viewposition
  }
  const handleTouchMove = (e: React.TouchEvent) => {
    const dt = (s.touch.startY - e.targetTouches[0].clientY) / TracksState.timeHeightFactor
    let target = s.touch.startPos - dt
    if (target < 0) target = 0
    if (target > PlayState.duration) target = PlayState.duration
    if (TracksState.tracking) seek(target)
    else TracksState.viewposition = target
  }
  const handleTouchEnd = () => {
    s.touch.touching = false
  }

  const handleDragNote = useCallback((tpid = "", noteid = "", slideid = "") => {
    s.dropnote.tpid = tpid
    s.dropnote.noteid = noteid
    s.dropnote.slideid = slideid
  }, [s])

  const handleNewSlideMid = useCallback((tpid: string, slideid: string) => {
    if (s.mouse.lane < 0) return
    const t = nearestBeatTime(s.mouse.time, TracksState.division)
    if (!t || t.timepoint !== tpid) return
    Actions.addSlideMid(tpid, slideid, s.mouse.lane, t.beatoffset, uuid())
  }, [s])

  const basicLinesPart = () => {
    const timeList = MakeArray(s.paddedDuration, 0, 2)
    return <>
      <div className={cn.layer}>
        {VerticalLineLefts.map(x =>
          <div key={x} className={cn.line} style={{ left: x + "%" }}></div>)}
      </div>
      <div className={cn.layer}>
        {timeList.map(x =>
          <div key={x} className={cn.time} style={{ bottom: s.bottompx(x) }}>{TimeToString(x)}</div>)}
      </div>
      <div className={cn.layer}>
        {GameMapState.map.timepoints.map(tp =>
          <div className={cn.timepoint} key={tp.id} style={{ bottom: s.bottompx(tp.offset) }}>
            <div style={{ position: "absolute", left: 0 }}>{TimeToString(tp.offset)}</div>
            <div style={{ position: "absolute", right: 0 }}>{tp.bpm}</div>
          </div>)}
      </div>
    </>
  }

  const previewNotePart = () =>
    <div className={cn.layer} style={{ transform: TracksState.mirror ? "scaleX(-1)" : undefined }}>
      {s.previewNote &&
        <img className={clsx(ncn.note, ncn.preview)} {...s.previewNote} alt=""></img>}
      {s.previewNote && s.previewSlide.style &&
        <img className={clsx(ncn.note, ncn.preview)} src={s.previewNote.src} style={s.previewSlide.style} alt=""></img>}
    </div>

  const beatlines = useMemo(() => <BeatLines />, [])
  const progressline = useMemo(() => <ProgressLine />, [])
  const noteslayer = useMemo(() =>
    <NotesLayer className={cn.layer}
      onAddSlideMid={handleNewSlideMid} onDragNote={handleDragNote}></NotesLayer>
    , [handleNewSlideMid, handleDragNote, cn])

  return useObserver(() => (
    <div className={className} onWheel={handleScroll} onTouchStart={handleTouchStart}
      onTouchMove={handleTouchMove} onTouchEnd={handleTouchEnd} onTouchCancel={handleTouchEnd}>
      <div className={cn.panel} ref={panelref} onMouseMove={handleMouseMove} onClick={handleClick}
        onDragOver={handleDragOver} onDrop={handleDrop} style={s.panelStyle}>
        {basicLinesPart()}
        <div className={cn.layer}>
          {beatlines}
        </div>
        {previewNotePart()}
        <div className={cn.layer}>
          {progressline}
        </div>
        {noteslayer}
      </div>
    </div>
  ))
}
