// bangbangboom-webapp/src/Pages/Components/DateTime.tsx
import React, { useState } from "react"
import { FormattedMessage, FormattedDate } from "react-intl"

export type DateTimeProps = { date: string | Date }

const oneminute = 60 * 1000
const onehour = 60 * 60 * 1000

export const DateTime = ({ date }: DateTimeProps) => {

  const d = typeof date === "string" ? new Date(date) : date

  const [display, setDisplay] = useState(null as React.ReactNode)

  const update = () => {
    const now = new Date();
    const diff = now.getTime() - d.getTime();
    if (diff < onehour) {
      const minute = Math.ceil(diff / oneminute);
      const next = minute * oneminute - diff;
      setDisplay(<FormattedMessage id="number.minutesago" values={{ count: minute }} />)
      setTimeout(update, next);
    } else if (diff < 24 * onehour) {
      const hour = Math.ceil(diff / onehour);
      const next = hour * onehour - diff;
      setDisplay(<FormattedMessage id="number.minutesago" values={{ count: hour }} />)
      setTimeout(update, next);
    } else {
      setDisplay(<FormattedDate value={d} />)
    } aqa
  }

  return display
}

// bangbangboom-webapp/src/components/others/datetime.vue
<template>
    <div class="date">
        <div>{{display}}</div>
        <md-tooltip md-direction="top">{{datestring}}</md-tooltip>
    </div>
</template>

<script lang="ts">
import Vue from "vue";
export default Vue.extend({
    props: { time: String },
    data() {
        return {
            display: ""
        };
    },
    computed: {
        date(): Date {
            return new Date(this.time);
        },
        datestring(): string {
            return this.date.toLocaleString();
        }
    },
    methods: {
        update() {
            const now = new Date();
            const diff = now.getTime() - this.date.getTime();
            if (diff < 60 * 60 * 1000) {
                const minute = Math.ceil(diff / 60 / 1000);
                const next = minute * 60 * 1000 - diff;
                this.display = this.$tc("c.minutesago", minute);
                setTimeout(this.update, next);
            } else if (diff < 24 * 60 * 60 * 1000) {
                const hour = Math.ceil(diff / 60 / 60 / 1000);
                const next = hour * 60 * 60 * 1000 - diff;
                this.display = this.$tc("c.hoursago", hour);
                setTimeout(this.update, next);
            } else {
                this.display = this.date.toLocaleDateString();
            }
        }
    },
    mounted() {
        this.update();
        this.$watch(() => this.$i18n.locale, () => this.update())
    }
});
</script>

<style scoped>
.date {
    position: relative;
    display: inline-block;
    text-align: center;
}
</style>
